diff -up ./Makefile ../multitail-5.2.12.p/Makefile
--- ./Makefile	2013-01-16 11:56:10.000000000 +0000
+++ ../multitail-5.2.12.p/Makefile	2013-05-07 20:21:48.739039617 +0000
@@ -1,7 +1,7 @@
 include version
 
 DESTDIR=/
-CONFIG_FILE=$(DESTDIR)/etc/multitail.conf
+CONFIG_FILE=$(DESTDIR)/usr/etc/multitail.conf
 
 CC=gcc
 DEBUG=-g # -D_DEBUG # -pg #  -D_DEBUG  #-pg -W -pedantic # -pg #-fprofile-arcs
@@ -20,19 +20,15 @@ multitail_ccmalloc: $(OBJS)
 	ccmalloc --no-wrapper $(CC) -Wall -W $(OBJS) $(LDFLAGS) -o ccmultitail
 
 install: multitail
-	cp multitail $(DESTDIR)/usr/bin
-	cp multitail.1 $(DESTDIR)/usr/share/man/man1/multitail.1
-	mkdir -p $(DESTDIR)/usr/share/doc/multitail-$(VERSION)
-	cp *.txt INSTALL manual*.html $(DESTDIR)/usr/share/doc/multitail-$(VERSION)
+	install -D -m 0755 multitail $(DESTDIR)/usr/bin/multitail
+	install -D -m 0644 multitail.1 $(DESTDIR)/usr/man/man1/multitail.1
 	#
 	### COPIED multitail.conf.new, YOU NEED TO REPLACE THE multitail.conf
 	### YOURSELF WITH THE NEW FILE
 	#
-	cp multitail.conf $(CONFIG_FILE).new
-	mkdir -p $(DESTDIR)/etc/multitail/
-	cp convert-* colors-* $(DESTDIR)/etc/multitail/
-	rm -f $(DESTDIR)/usr/share/man/man1/multitail.1.gz
-	gzip -9 $(DESTDIR)/usr/share/man/man1/multitail.1
+	install -D -m 0644 multitail.conf $(DESTDIR)/usr/etc/multitail.conf
+	install -d $(DESTDIR)/usr/etc/multitail
+	cp convert-* colors-* $(DESTDIR)/usr/etc/multitail
 	#
 	# There's a mailinglist!
 	# Send an e-mail to minimalist@vanheusden.com with in the subject
